### ISSUE TITLE
-dlEncrypted works but the decrypted version doesn't

### ISSUE THREAD

**Issue by zonzille** [Maschell/JNUSTool#13]
Hello ! 

After dozens of tries I can repeat the exact same behaviour for which I haven't found any workaround.

When downloading a game with the -dlEncrypted option everything runs nicely and I have my tmp_titleid folders full of .h3 and .app files. However running the "titleid titlekey -file ./*" one produces nothing but an empty folder. The folder created has the correct name of the game and the terminal output seems to indicate that all is done, but it's over in a second and produces no file whatsoever.

I have tried the workaround of putting the correct title.tmd in the tmp_titleid folder but it didnt change anything.

Here's the output of which I have erased the titlekey : 

`JNUSTool 0.3b - by Maschell`

`Using cached TMD.`
`Using ticket from parameter.`
`Using cached FST`
`Decrypting meta.xml`

`Title                           : The Legend of Zelda Breath of the Wild [ALZP01]`
`TitleID                         : 00050000101C9500`
`Version                         : 0000000000000001`
`Encrypted Key                   : `
`Decrypted Key                   : `
`Total Size of Content Files     : 10041.4 MB`
`Total Size of Decrypted Files   : 9883.59 MB`
`Entries                         : 19394`
`Files                           : 18719`
`Files in NUS-Title              : 18719`
`Done!`

My java version is openjdk 1.8.0_232-solus running on GNU/Linux distro Solus on the rolling release version with kernel 5.5.11-151.current

Also it could be useful to tell that maven isn't a thing on my distro and so I use JNUSTool as it was cloned from this github repo, with the common key added in the config file. IDK if it's necessary to have maven but downloading the encrypted files worked without it so...

Hope it makes sense to someone !

EDIT : when I try without copying the title.tmd file myself, the terminal says `Getting missing tmd from Server!` but the file doesn't appear in the folder. Also I don't have meta.xml, or I'm unable to find it

**Comment by Maschell** [comment]
I personally wouldn't use JNUSTool anymore. It's known to have several bugs.

I have written all a java lib called [JNUSLib](https://github.com/Maschell/JNUSLib/blob/master/README.md) which has the same features as JNUSTool, plus many more. There are some small 
command line examples which use this lib to decrypt files, like the [JNUSLibDecryptor](https://github.com/Maschell/JNUSLibDecryptor) or the [NUSFileDownloader](https://github.com/wiiu-env/NUSFileDownloader)

**Comment by zonzille** [comment]
Oh, sorry I didn't know this lib existed. Thank you for your quick answer and sorry for the disturbance !
